### ISSUE TITLE
Update supported instance types

### ISSUE THREAD

**Issue by kwoodson** [openshift/cluster-api-provider-alibaba#6]
@menglingwei @elmiko @JoelSpeed 

When attempting to deploy today I ran into an error regarding our current instance type generation:

```
E1004 13:29:34.553092 1161362 controller.go:123] Unable to set scale from zero annotations: unknown instance type: %secs.g6.large
E1004 13:29:34.553105 1161362 controller.go:124] Autoscaling from zero will not work. To fix this, manually populate machine annotations for your instance type: %v[machine.openshift.io/vCPU machine.openshift.io/memoryMb machine.openshift.io/GPU]
```

We need to augment these to include the `ecs.g6` machines (https://www.alibabacloud.com/help/doc-detail/25378.html#g6)
https://github.com/openshift/cluster-api-provider-alibaba/blob/main/pkg/actuators/machineset/ecs_instance_types.go#L25-L32

The `ecs.c6` are compute optimized. The `g` is for general purpose.

**Comment by menglingwei** [comment]
@kwoodson Let me fix it after the National Day holiday
