### ISSUE TITLE
controlplane node matching

### ISSUE THREAD

**Issue by kwoodson** [openshift/cluster-api-provider-alibaba#7]
@elmiko @menglingwei 
I noticed when starting the machine-controller-manager that the control plane nodes were not reconciling.

```
I1004 13:46:11.073433 1254535 controller.go:174] test-dpzrt-master-0: reconciling Machine
W1004 13:46:11.073451 1254535 controller.go:275] test-dpzrt-master-0: machine has gone "Failed" phase. It won't reconcile
I1004 13:46:11.073481 1254535 controller.go:174] test-dpzrt-master-1: reconciling Machine
W1004 13:46:11.073494 1254535 controller.go:275] test-dpzrt-master-1: machine has gone "Failed" phase. It won't reconcile
I1004 13:46:11.073510 1254535 controller.go:174] test-dpzrt-master-2: reconciling Machine
```
Actual instance names:
```
test-dpzrt-master2
test-dpzrt-master1
test-dpzrt-master3
```
There is a difference in format with the last `-`. We have also modified the control plane nodes to have different kubelet names in the machine-config-operator. What is the path way forward for these? Do we just ignore these?

**Comment by menglingwei** [comment]
@kwoodson Any other error messages?

**Comment by elmiko** [comment]
is there also an _off by one error_ happening with those control plane instance names?

**Comment by kwoodson** [comment]
@elmiko Good catch. Two items here in the same issue.

https://github.com/openshift/installer/pull/5018/files#diff-f521c20910158e3d15160678e61225df2b4812d47c4881faed6bfcd064be7e30R14

This requires an update and I will attempt to add more info. They are missing a `-` and also the count is off by 1. I'll test it and then put a note in about a fix.
